---
title: "2.0-data-cleaning-for-analysis"
author: "Julian Beckert"
format: html
editor: visual
---

## Libraries & datasets

```{r}
library(tidyverse)

# Bus ridership and departures with census tracts
censustract_ridership_calendar <- read_csv("censustract_buses_ridership_calendar.csv")
# American Community Survey
acs <- read_csv("all_american_community_survey.csv")
# Residential buildings with BRT and existing bus route/stop distances
residential <- read_csv("residentialbuilidings_BRT_distance_census_tracts.csv")
# Basic data on the cities and size in square miles for each census tract
city_tract_size <- read_csv("censusandcitysize.csv")
# BRT statistics
brt_stop_statistics <- read_csv("brt_stop_statistics.csv")
# amount of land near bus stops
land_near_bus_stop <- read_csv("tracts_with_sqmiles_land_near_bus_stops.csv")

# stops per census tracts
all_stops <- read_csv("bus_stops_in_tracts.csv")
```

## Distance summary

```{r}
residential_distance_summary <- residential %>% 
  group_by(Geography) %>% 
  summarise(
   
    totalBuildings = n(),
    totalDwellings = sum(NO_DWELLINGS),
    
    halfm_stop_totalBuildings = sum(halfmile_stop == 1), # total number of rows (residential buildings) where halfmile is true
    halfm_stop_totalDwellings = sum(NO_DWELLINGS[halfmile_stop == 1]), # total sum of "NO_DWELLINGS" values in rows where halfmile is true

    quarterm_stop_totalBuildings = sum(quartermile_stop == 1),
    quarterm_stop_totalDwellings = sum(NO_DWELLINGS[quartermile_stop == 1]),
    
    halfm_ROUTE_totalBuildings = sum(halfmile_route == 1), 
    halfm_ROUTE_totalDwellings = sum(NO_DWELLINGS[halfmile_route == 1]), 

    quarterm_ROUTE_totalBuildings = sum(quartermile_route == 1),
    quarterm_ROUTE_totalDwellings = sum(NO_DWELLINGS[quartermile_route == 1]),

    
    nobus_stop_totalBuildings = sum(halfmile_stop == 0), # if there's no stops in up to 1/2 mile, there are no stops in 1/4 mile either
    nobus_stop_totalDwellings = sum(NO_DWELLINGS[halfmile_stop == 0]),
    
    nobus_ROUTE_totalBuildings = sum(halfmile_route == 0), # if there's no routes in up to 1/2 mile, there are no routes in 1/4 mile either
    nobus_ROUTE_totalDwellings = sum(NO_DWELLINGS[halfmile_route == 0]),
    
    halfm_stop_BRT_totalBuildings = sum(halfmile_BRT_stop == 1),
    halfm_stop_BRT_totalDwellings = sum(NO_DWELLINGS[halfmile_BRT_stop == 1]),
    
    quarterm_stop_BRT_totalBuildings = sum(quartermile_BRT_stop == 1),
    quarterm_stop_BRT_totalDwellings = sum(NO_DWELLINGS[quartermile_BRT_stop == 1]),
    
    
    Building_halfm_ROUTE_no_stop = sum(halfmile_route == 1 & halfmile_stop == 0 &
                                              quartermile_stop == 0),

    Dwell_halfm_ROUTE_no_stop = sum(NO_DWELLINGS[halfmile_route == 1 & halfmile_stop == 0 & quartermile_stop == 0]),

    Building_quarterm_ROUTE_no_stop = sum(quartermile_route == 1 & quartermile_stop == 0),
    
    Dwell_quarterm_ROUTE_no_stop = sum(NO_DWELLINGS[quartermile_route == 1 & quartermile_stop == 0]),
    
    
    # homes that have a bus passing by within 1/4 mile, but not stopping within 1/4 mile, or even within 1/2 mile
    # in other words, this is the proportion of homes in this tract that have a bus passing by in walking distance but stopping more than half a mile away
    Building_quarterm_ROUTE_no_stop_at_ALL = sum(quartermile_route == 1 & quartermile_stop == 0 & halfmile_stop == 0),
    Dwell_quarterm_ROUTE_no_stop_at_ALL = sum(NO_DWELLINGS[quartermile_route == 1 & quartermile_stop == 0 & halfmile_stop == 0]),
    
    
    propBuilding_quarterm_stop = quarterm_stop_totalBuildings/totalBuildings,
    propDwell_quarterm_stop = quarterm_stop_totalDwellings/totalDwellings,
    
    propBuilding_halfm_stop = halfm_stop_totalBuildings/totalBuildings,
    propDwell_halfm_stop = halfm_stop_totalDwellings/totalDwellings,
    
    propBuilding_quarterm_ROUTE = quarterm_ROUTE_totalBuildings/totalBuildings,
    propDwell_quarterm_ROUTE = quarterm_ROUTE_totalDwellings/totalDwellings,

    propBuilding_halfm_ROUTE = halfm_ROUTE_totalBuildings/totalBuildings,
    propDwell_halfm_ROUTE = halfm_ROUTE_totalDwellings/totalDwellings,
    
    propBuilding_nobus_stop = nobus_stop_totalBuildings/totalBuildings, # proportion of the total buildings in the tract that have no bus stops in up to 1/2 mile
    propDwell_nobus_stop = nobus_stop_totalDwellings/totalDwellings, # proportion of the total dwellings in the tract that have no bus stops in up to 1/2 mile
    
    propBuilding_nobus_ROUTE = nobus_ROUTE_totalBuildings/totalBuildings,
    propDwell_nobus_ROUTE = nobus_ROUTE_totalDwellings/totalDwellings,

    
    propBuilding_halfm_ROUTE_no_stop = Building_halfm_ROUTE_no_stop/totalBuildings,

    propDwell_halfm_ROUTE_no_stop = Dwell_halfm_ROUTE_no_stop/totalDwellings,

    propBuilding_quarterm_ROUTE_no_stop = Building_quarterm_ROUTE_no_stop/totalBuildings,
    
    propDwell_quarterm_ROUTE_no_stop = Dwell_quarterm_ROUTE_no_stop/totalDwellings,
    
    
    propBuilding_quarterm_ROUTE_no_stop_at_ALL = Building_quarterm_ROUTE_no_stop_at_ALL/totalBuildings,
    propDwell_quarterm_ROUTE_no_stop_at_ALL = Dwell_quarterm_ROUTE_no_stop_at_ALL/totalDwellings,
    
    propBuilding_halfm_BRT_stop = halfm_stop_BRT_totalBuildings/totalBuildings,
    propDwell_halfm_BRT_stop = halfm_stop_BRT_totalDwellings/totalDwellings,
    
    propBuilding_quarterm_BRT_stop = quarterm_stop_BRT_totalBuildings/totalBuildings,
    propDwell_quarterm_BRT_stop = quarterm_stop_BRT_totalDwellings/totalDwellings
     
  )

```

## Ridership/departures

```{r}
ridership_calendar_clean <- censustract_ridership_calendar %>% 
  select(-DESCRIPTIO, -RT_D, -ROUTE, -ORIGIN, -DESTINATIO, -GEOMETRYSO, -OBJECTID, -SHAPE_ID, -SHAPELEN, -route_desc, -route_text_color, -route_type_text)

ridership_distance_summary <- left_join(residential_distance_summary, ridership_calendar_clean)

clean_ridership_distance_summary <- ridership_distance_summary

# replace NAs created by the join with 0
clean_ridership_distance_summary[c("wkday_departures", "sat_departures", "sun_departures", "wkday_riders", "sat_riders", "sun_riders")][is.na(clean_ridership_distance_summary[c("wkday_departures", "sat_departures", "sun_departures", "wkday_riders", "sat_riders", "sun_riders")])] <- 0
# this code is taken from a Stack Overflow answer: https://stackoverflow.com/a/19379400

routes_tracts_summary <- clean_ridership_distance_summary %>% 
  group_by(Geography) %>% 
  summarise(totalRoutes = n(), # this works for all tracts that actually have bus routes - if there aren't any bus routes, it will fill in 1. this gets fixed after this dataframe is created
            
            # total mean daily riders for all routes that cross through the tract
            totalMeanWkdayRouteRiders = sum(wkday_riders),
            totalMeanSatRouteRiders = sum(sat_riders),
            totalMeanSunRouteRiders = sum(sun_riders),

            # average mean daily riders across the routes that cross through the tract
            meanMeanWkdayRouteRiders = round(mean(wkday_riders)),
            meanMeanSatRoudeRiders = round(mean(sat_riders)),
            meanMeanSunRouteRiders = round(mean(sun_riders)),
            
            totalWkdayDepartures = sum(wkday_departures),
            totalSatDepartures = sum(sat_departures),
            totalSunDepartures = sum(sun_departures),
            
            meanWkdayDepartures = round(mean(wkday_departures)),
            medianWkdayDepartures = round(median(wkday_departures)),
            
            is_sunday = ifelse(
              totalSunDepartures == 0, 0, 1
              ),
            is_sat_not_sun = ifelse(
              totalSatDepartures+totalSunDepartures == 0, 0, 1
            ),
            
            routes_wmata = ifelse(
              # using ifelse() to avoid NAs and fill 0s in their place
              !is.na(sum(agency == "WMATA")), sum(agency == "WMATA"), 0
              ),
            routes_rideon = ifelse(
              !is.na(sum(agency == "MC RideOn")), sum(agency == "MC RideOn"), 0
              ),
            most_agency = ifelse(
              routes_wmata > routes_rideon, "WMATA", "RideOn"
            )
  )

routes_tracts_summary <- routes_tracts_summary %>% 
  mutate(
    # copy of totalRoutes that checks if there are actually buses - if there are 0 departures, then there are no buses, and the existing value will be replaced with 0
    Totalroute = ifelse(
    totalWkdayDepartures == 0 & totalSatDepartures == 0 & totalSunDepartures == 0, 0, totalRoutes)) %>% 
  # replace totalRoutes with this new column
  relocate(Totalroute, .after = totalRoutes) %>% 
  select(-totalRoutes) %>% 
  rename_at("Totalroute",~"totalRoutes")
```

## Join to census (ACS) data on household size

```{r}
# join 1
routes_tracts_distance <- left_join(residential_distance_summary, routes_tracts_summary)
# join 2
routes_tracts_household <- left_join(routes_tracts_distance, acs)


# replace NA with 0
routes_tracts_household[c("routes_wmata", "routes_rideon")][is.na(routes_tracts_household[c("routes_wmata", "routes_rideon")])] <- 0

routes_tracts_household <- routes_tracts_household %>% select(-TractName) # this will be replaced with a similar column in the cities/size dataset

```

## Add "need"

```{r}
need_routes_tracts_households <- routes_tracts_household %>% 
  mutate(
    # make a copy of these three columns with different names:
    estPopulation = dmgEstTotPop,
    estHouseholds = hsnwEstTot,
    
    estPopChildren14Under = dmgEstTotPopUnder5Yrs+dmgEstTotPop5to9Yrs+dmgEstTotPop10to14Yrs,
    estPopElderly65Over = dmgEstTotPop65to74Yrs+dmgEstTotPop75to84Yrs+dmgEstTotPop85YrsAndOver,
    
    # number of vehicles variables
    estHouseholds_0Vehicle = hsEstTot0Vehicle, # renaming
    #
    estHouseholds_MorePeopleThanVehicles = hsEstTot0Vehicle+hsEstTot4ormoreperson1Vehicle+hsEstTot4ormoreperson2Vehicles+hsEstTot4ormoreperson3Vehicles+hsEstTot3person2Vehicles+hsEstTot3person1Vehicle+hsEstTot2person1Vehicle,
    #
    estHouseholds_LessVehiclesThanWorkers = nwEstTot1_worker0Vehicle_+nwEstTot2_workers0Vehicle_+nwEstTot3Plusworkers0Vehicle_+nwEstTot2_workers1_Vehicle_+nwEstTot3Plusworkers1_Vehicle_+nwEstTot3Plusworkers2_Vehicles_,
    #
    estHouseholds_1Vehicle_2PlusPeople = hsEstTot4ormoreperson1Vehicle+hsEstTot3person1Vehicle+hsEstTot2person1Vehicle,
    #
    estHouseholds_2Vehicle_3PlusPeople = hsEstTot3person2Vehicles+hsEstTot4ormoreperson2Vehicles,
    #
    estHouseholds_2PlusWorkers1Vehicle = nwEstTot2_workers1_Vehicle_+nwEstTot3Plusworkers1_Vehicle_,
    #
    estHouseholds_2PlusWorkers0Vehicles = nwEstTot2_workers0Vehicle_+nwEstTot3Plusworkers0Vehicle_,
    
    
    # household proportions
    propEstHouseholds_0Vehicle = estHouseholds_0Vehicle/estHouseholds,
    propEstHouseholds_MorePeopleThanVehicles = estHouseholds_MorePeopleThanVehicles/estHouseholds,
    propEstHouseholds_LessVehiclesThanWorkers = estHouseholds_LessVehiclesThanWorkers/estHouseholds,
    
    # demographics proportions
    propEstPopChildren14Under = estPopChildren14Under/estPopulation,
    propEstPopElderly65Over = estPopElderly65Over/estPopulation
  )

# simplify
namecheck <- tibble(col = names(need_routes_tracts_households))
need_routes_tracts_households_simpler <- need_routes_tracts_households %>% 
  select(c(1:64, 214:229))
newnames <- tibble(col = names(need_routes_tracts_households_simpler))
```

## Join to tract details

Cities, typical tract name, size

```{r}
# with city names and size (this duplicates a lot of rows, so it isn't very useful)
DESCRIPTION_need_routes_tracts_households_simpler <- left_join(need_routes_tracts_households_simpler, city_tract_size, by = "Geography")


# with size only
succinct_need_routes_tracts_households_simpler <- left_join(need_routes_tracts_households_simpler, city_tract_size %>% 
                                                              select(Geography, SquareMile) %>% 
                                                          distinct(Geography, .keep_all = TRUE), by = "Geography")


succinct_need_routes_tracts_households <- 
  succinct_need_routes_tracts_households_simpler %>%
  filter(!is.na(Geography)) %>% 
  relocate(c(SquareMile), .after = Geography)
```

## Add BRT binary

```{r}
succinct_brt <- left_join(succinct_need_routes_tracts_households, brt_stop_statistics)
sum(is.na(succinct_brt$has_brt_stop))
succinct_brt_clean <- succinct_brt
# replaced NAs created by the join with 0
succinct_brt_clean$brt_stops[is.na(succinct_brt_clean$brt_stops)] <- 0
succinct_brt_clean$has_brt_stop[is.na(succinct_brt_clean$has_brt_stop)] <- 0

# the same thing, but it includes cities (resulting in duplicate rows)
succinct_brt_cities <- left_join(DESCRIPTION_need_routes_tracts_households_simpler %>% 
                                   filter(!is.na(Geography)), 
                                 brt_stop_statistics)
succinct_brt_cities_clean <- succinct_brt_cities
succinct_brt_cities_clean$brt_stops[is.na(succinct_brt_cities_clean$brt_stops)] <- 0
succinct_brt_cities_clean$has_brt_stop[is.na(succinct_brt_cities_clean$has_brt_stop)] <- 0
```

## Bus route grouped

```{r}
bus_tracts_merge <- merge(succinct_brt_cities_clean, censustract_ridership_calendar)

bus_tracts_summary <- bus_tracts_merge %>% 
  group_by(route_name) %>% 
  summarise(
    tracts = n_distinct(Geography),
    totalEstPopulation = sum(estPopulation),
    squareMilesOfTracts = sum(SquareMile),
    wkdayRiders = unique(wkday_riders),
    satRiders = unique(sat_riders),
    sunRiders = unique(sun_riders),
    weeklyTotalRiders = sum(wkdayRiders+satRiders+sunRiders),
    wkdayDepartures = unique(wkday_departures),
    satDepartures = unique(sat_departures),
    sunDepartures = unique(sun_departures),
    estHouseholdsTracts = sum(estHouseholds),
    estLessVehiclesTracts = sum(estHouseholds_LessVehiclesThanWorkers),
    estVehiclesTracts = sum(estHouseholds_0Vehicle),
    agency = unique(agency)
  )
```

## Add total stops & land near bus stops

```{r}
# land
join_land_near_bus_stop <- left_join(succinct_brt_clean, land_near_bus_stop %>%
                                  rename_at("GEOIDFQ",~"Geography") %>% 
                                  select(Geography, halfmile_area_SQMILES, quartermile_area_SQMILES))
land_bus_data <- join_land_near_bus_stop %>% 
  rename_at("quartermile_area_SQMILES",~"SquareMiles_fourthmile_fromstop") %>% 
  rename_at("halfmile_area_SQMILES",~"SquareMiles_halfmile_fromstop") %>% 
  mutate(
    prop_land_fourthmile_stop = round(SquareMiles_fourthmile_fromstop/SquareMile, 5),
    prop_land_halfmile_stop = round(SquareMiles_halfmile_fromstop/SquareMile, 5)
  ) %>% 
  relocate(c(SquareMiles_fourthmile_fromstop, prop_land_fourthmile_stop, prop_land_halfmile_stop), .after = SquareMile)

# stops in tracts
identical(all_stops$GEOIDFQ, all_stops$GEOIDFQ_1) # TRUE
stops_bus <- left_join(land_bus_data, all_stops %>%
                                  rename_at("GEOIDFQ_1",~"Geography"))

stops_bus_summary <- stops_bus %>% 
  group_by(Geography) %>% 
  summarise(
    totalStops = n()
  )


bus_stops_data <- left_join(land_bus_data, stops_bus_summary)

bus_stops_data <- bus_stops_data %>% 
  relocate(SquareMiles_halfmile_fromstop, .after = SquareMiles_fourthmile_fromstop)

# one of the tracts (located around damascus) has NA for all of the "half mile" related columns, and a 0 for all other nearby-bus-routes columns. replacing the NAs in the two half mile related columns with 0:
sum(is.na(bus_stops_data$SquareMiles_halfmile_fromstop))
bus_stops_data$SquareMiles_halfmile_fromstop[is.na(bus_stops_data$SquareMiles_halfmile_fromstop)] <- 0
sum(is.na(bus_stops_data$prop_land_halfmile_stop))
bus_stops_data$prop_land_halfmile_stop[is.na(bus_stops_data$prop_land_halfmile_stop)] <- 0


```

```{r}
# write_csv(bus_tracts_summary, "bus_tracts_acs_summary.csv")
```

## Download

```{r}
# write_csv(bus_stops_data, "final_bus_access_dataset_simple.csv")
```
